[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"      # or whatever Node version works locally
  NPM_FLAGS = "--global pnpm@9.1.4"

[[plugins]]
package = "@netlify/plugin-nextjs"
  [plugins.inputs]
  ignore_deprecations = false
